<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\AutomatedRecordingStoreRequest
 */
class AutomatedRecordingStoreRequestTest extends TestCase
{
    /** @var \App\Http\Requests\AutomatedRecordingStoreRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\AutomatedRecordingStoreRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'uuid' => [
                'required_without:file',
            ],
            'key' => [
                'required_without:file',
            ],
            'bucket' => [
                'required_without:file',
            ],
            'name' => [
                'required_without:file',
            ],
            'content_type' => [
                'required_without:file',
            ],
            'file' => [
                'required_without:uuid,key,bucket,name,content_type',
            ],
            'time' => [
                'required',
                'date',
            ],
            'frequency' => [
                'required',
                'numeric',
            ],
            'receiver' => [
                'nullable',
            ],
        ], $actual);
    }

    // test cases...
}
