<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\CommentStoreRequest
 */
class CommentStoreRequestTest extends TestCase
{
    /** @var \App\Http\Requests\CommentStoreRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\CommentStoreRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'message' => [
                'required',
                'string',
            ],
            'message_id' => [
                'exists:messages,id',
                'required_without:recording_id',
            ],
            'recording_id' => [
                'exists:recordings,id',
                'required_without:message_id',
            ],
        ], $actual);
    }

    // test cases...
}
