<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\MessageUpdateRequest
 */
class MessageUpdateRequestTest extends TestCase
{
    /** @var \App\Http\Requests\MessageUpdateRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\MessageUpdateRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'type' => [
                'nullable',
            ],
            'sender' => [
                'nullable',
                'string',
            ],
            'receiver' => [
                'nullable',
                'string',
            ],
            'time' => [
                'nullable',
                'date',
            ],
            'message' => [
                'nullable',
                'string',
            ],
        ], $actual);
    }

    // test cases...
}
