<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 9bee2536-7421-466a-a95b-6ca0fbe13f2a-02
 * Migration datetime: 2020-01-10 02:35:23.323539
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations022020011002352332 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('relays', function (Blueprint $table) {
            $table->foreign('message_id')->references('id')->on('messages');
        });
        Schema::table('relays', function (Blueprint $table) {
            $table->foreign('relay_provider_id')->references('id')->on('relay_providers');
        });
        Schema::table('relay_providers', function (Blueprint $table) {
            $table->foreign('user_id')->references('id')->on('users');
        });
        Schema::table('comments', function (Blueprint $table) {
            $table->foreign('parent_comment_id')->references('id')->on('comments');
        });
        Schema::table('recordings', function (Blueprint $table) {
            $table->foreign('message_id')->references('id')->on('messages');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('recordings')) {
            Schema::table('recordings', function (Blueprint $table) {
                $table->dropForeign(['message_id']);
            });
        }
        if (Schema::hasTable('comments')) {
            Schema::table('comments', function (Blueprint $table) {
                $table->dropForeign(['parent_comment_id']);
            });
        }
        if (Schema::hasTable('relay_providers')) {
            Schema::table('relay_providers', function (Blueprint $table) {
                $table->dropForeign(['user_id']);
            });
        }
        if (Schema::hasTable('relays')) {
            Schema::table('relays', function (Blueprint $table) {
                $table->dropForeign(['relay_provider_id']);
            });
        }
        if (Schema::hasTable('relays')) {
            Schema::table('relays', function (Blueprint $table) {
                $table->dropForeign(['message_id']);
            });
        }
    }
}
